meta_product_name: "Podcast Database"
meta_title: "Podcast Database -  The World's Podcast Database"
meta_description: "Find the best Podcast Episodes in the world!"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
